/**
 * SSDI subscription tiers — display config aligned with backend pricing.
 */

export const SSDI_PLANS = [
  {
    id: "free",
    name: "Free",
    tagline: "Pay only when you connect a user",
    price: 0,
    priceLabel: "₹0",
    priceUnit: "per month",
    billingNote: "₹0/month base · ₹150 one-time per connected user",
    userLimit: null,
    userLimitLabel: "Unlimited connections (pay per user)",
    perUserPrice: 150,
    perUserLabel: "₹150 one-time per connected user",
    accent: "free",
    popular: false,
    features: [
      "₹0 per month base plan",
      "₹150 one-time fee per connected user",
      "Connect users on demand",
      "Core CRM access for your company",
    ],
  },
  {
    id: "silver",
    name: "Silver",
    tagline: "Growing teams",
    price: 5000,
    priceLabel: "₹5,000",
    priceUnit: "per month",
    billingNote: "₹5,000/month flat — connect up to 50 users",
    userLimit: 50,
    userLimitLabel: "Up to 50 connected users",
    perUserPrice: null,
    perUserLabel: "Included in monthly plan",
    accent: "silver",
    popular: false,
    features: [
      "Connect up to 50 users",
      "₹5,000 per month flat (no per-user fee)",
      "Scheme stops when 50-user limit is reached",
      "Standard support",
    ],
  },
  {
    id: "golden",
    name: "Golden",
    tagline: "Scale your operations",
    price: 15000,
    priceLabel: "₹15,000",
    priceUnit: "per month",
    billingNote: "₹15,000/month flat — connect up to 100 users",
    userLimit: 100,
    userLimitLabel: "Up to 100 connected users",
    perUserPrice: null,
    perUserLabel: "Included in monthly plan",
    accent: "golden",
    popular: true,
    features: [
      "Connect up to 100 users",
      "₹15,000 per month flat",
      "Scheme stops when 100-user limit is reached",
      "Priority support",
    ],
  },
  {
    id: "platinum",
    name: "Platinum",
    tagline: "Unlimited scale",
    price: null,
    priceLabel: "Custom",
    priceUnit: "per month",
    billingNote: "Custom monthly pricing — unlimited connected users",
    userLimit: null,
    userLimitLabel: "Unlimited connected users",
    perUserPrice: null,
    perUserLabel: "Unlimited users included",
    accent: "platinum",
    popular: false,
    features: [
      "Unlimited user connections",
      "Custom price per month",
      "Dedicated account manager",
      "24/7 priority support",
    ],
  },
];

export const PLAN_COMPARISON_ROWS = [
  {
    label: "Monthly fee",
    free: "₹0 / month",
    silver: "₹5,000 / month",
    golden: "₹15,000 / month",
    platinum: "Custom / month",
  },
  {
    label: "Per-user connect fee",
    free: "₹150 (one-time)",
    silver: "Included",
    golden: "Included",
    platinum: "Included",
  },
  {
    label: "Max connected users",
    free: "Unlimited*",
    silver: "50",
    golden: "100",
    platinum: "Unlimited",
  },
  {
    label: "At limit",
    free: "—",
    silver: "Scheme stops — upgrade required",
    golden: "Scheme stops — upgrade required",
    platinum: "—",
  },
];
